version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: webkt-db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always    
    ports:
      - "5200:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: webkt
      MYSQL_USER: webkt
      MYSQL_PASSWORD: whatismysql888
    networks:
      - mysqlnet

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: webkt-phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    networks:
      - mysqlnet

volumes:
  mysql_data:

networks:
  mysqlnet: